### ISSUE TITLE
Support Linux, MacOS

### ISSUE THREAD

**Issue by serin-delaunay** [serin-delaunay/Wangscape#16]
I don't have any hardware that can run MacOS, or any spare partitions to install Linux on. So this will not be happening any time soon unless someone else does it.

**Comment by hryniuk** [comment]
Hi, @serin-delaunay, I could help you with it (and maybe with other issues as soon as it will compile on Linux).

I've started building Wangscape with:
```shell
g++ *.cpp -I /usr/include --std=c++14 -lboost_system -lsfml-graphics -lsfml-window -lsfml-system -lboost_filesystem
```
and I got bunch of errors:
```
In file included from Interval.h:2:0,
                 from Interval.cpp:1:
common.h:9:8: error: ‘size_t’ does not name a type
 static size_t const CORNERS = 4;
        ^~~~~~
Options.cpp: In member function ‘void Options::initialise(const Document&)’:
Options.cpp:38:26: error: invalid initialization of non-const reference of type ‘rapidjson::GenericObject<true, rapidjson::GenericValue<rapidjson::UTF8<> > >&’ from an rvalue of type ‘rapidjson::GenericValue<rapidjson::UTF8<> >::ConstObject {aka rapidjson::GenericObject<true, rapidjson::GenericValue<rapidjson::UTF8<> > >}’
     auto& o = d.GetObject();
               ~~~~~~~~~~~^~
Options.cpp:40:76: error: invalid initialization of non-const reference of type ‘rapidjson::GenericObject<true, rapidjson::GenericValue<rapidjson::UTF8<> > >&’ from an rvalue of type ‘rapidjson::GenericValue<rapidjson::UTF8<> >::ConstObject {aka rapidjson::GenericObject<true, rapidjson::GenericValue<rapidjson::UTF8<> > >}’
         auto& doc_tile_format = o.FindMember("TileFormat")->value.GetObject();
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
Options.cpp:49:75: error: invalid initialization of non-const reference of type ‘rapidjson::GenericObject<true, rapidjson::GenericValue<rapidjson::UTF8<> > >&’ from an rvalue of type ‘rapidjson::GenericValue<rapidjson::UTF8<> >::ConstObject {aka rapidjson::GenericObject<true, rapidjson::GenericValue<rapidjson::UTF8<> > >}’
         auto& doc_metaoutput = o.FindMember("MetaOutput")->value.GetObject();
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
Options.cpp:63:71: error: invalid initialization of non-const reference of type ‘rapidjson::GenericObject<true, rapidjson::GenericValue<rapidjson::UTF8<> > >&’ from an rvalue of type ‘rapidjson::GenericValue<rapidjson::UTF8<> >::ConstObject {aka rapidjson::GenericObject<true, rapidjson::GenericValue<rapidjson::UTF8<> > >}’
         auto& doc_terrains = o.FindMember("Terrains")->value.GetObject();
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
Options.cpp:78:68: error: invalid initialization of non-const reference of type ‘rapidjson::GenericArray<true, rapidjson::GenericValue<rapidjson::UTF8<> > >&’ from an rvalue of type ‘rapidjson::GenericValue<rapidjson::UTF8<> >::ConstArray {aka rapidjson::GenericArray<true, rapidjson::GenericValue<rapidjson::UTF8<> > >}’
         auto& doc_cliques = o.FindMember("Cliques")->value.GetArray();
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
Options.cpp:91:81: error: invalid initialization of non-const reference of type ‘rapidjson::GenericArray<true, rapidjson::GenericValue<rapidjson::UTF8<> > >&’ from an rvalue of type ‘rapidjson::GenericValue<rapidjson::UTF8<> >::ConstArray {aka rapidjson::GenericArray<true, rapidjson::GenericValue<rapidjson::UTF8<> > >}’
         auto& doc_border_offsets = o.FindMember("BorderOffsets")->value.GetArray();
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from TileGenerator.cpp:3:0:
TilePartitionGradient.h:3:29: fatal error: sfml/Graphics.hpp: No such file or directory
 #include <sfml/Graphics.hpp>
                             ^
compilation terminated.
In file included from TilePartitionGradient.cpp:1:0:
TilePartitionGradient.h:3:29: fatal error: sfml/Graphics.hpp: No such file or directory
 #include <sfml/Graphics.hpp>
                             ^
compilation terminated.
```

The first problem are includes. While standard **SFML** distribution uses capital letters, you include `sfml/*` in source files. After fixing it (`sfml` -> `SFML`), I had removed `&` from `auto` (it seems that it were references to temporary values), I built it again and I got only linking errors:

```shell
/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/tmp/ccZSAnDP.o: In function `TilesetGenerator::TilesetGenerator(Options const&)':
TilesetGenerator.cpp:(.text+0x3e): undefined reference to `MetaOutput::MetaOutput()'
TilesetGenerator.cpp:(.text+0x53): undefined reference to `TerrainImages::TerrainImages()'
TilesetGenerator.cpp:(.text+0x151): undefined reference to `TerrainImages::addTerrain(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long)'
TilesetGenerator.cpp:(.text+0x1de): undefined reference to `TerrainImages::~TerrainImages()'
TilesetGenerator.cpp:(.text+0x1f6): undefined reference to `MetaOutput::~MetaOutput()'
/tmp/ccZSAnDP.o: In function `TilesetGenerator::~TilesetGenerator()':
TilesetGenerator.cpp:(.text+0x22c): undefined reference to `TerrainImages::~TerrainImages()'
TilesetGenerator.cpp:(.text+0x23c): undefined reference to `MetaOutput::~MetaOutput()'
/tmp/ccZSAnDP.o: In function `TilesetGenerator::generate(std::function<void (sf::Texture const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>)':
TilesetGenerator.cpp:(.text+0x281): undefined reference to `MetaOutput::setResolution(unsigned long)'
TilesetGenerator.cpp:(.text+0x587): undefined reference to `MetaOutput::addTileset(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long)'
TilesetGenerator.cpp:(.text+0x5b1): undefined reference to `TileGenerator::generate(sf::RenderTexture&, unsigned long, unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, TerrainImages const&, Options const&)'
/tmp/ccZSAnDP.o: In function `TilesetGenerator::generateClique(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, sf::RenderTexture&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::function<void (sf::RenderTexture&, unsigned long, unsigned long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, TerrainImages const&, Options const&)>)':
TilesetGenerator.cpp:(.text+0xaa8): undefined reference to `MetaOutput::addTile(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long)'
collect2: error: ld returned 1 exit status
```

I'm almost sure that you forgot to push **MetaOutput.cpp**, **TerrainImages.cpp** and **TilesetGenerator.cpp**. If you provide them :wink:, I will check it again and I'll try to provide **CMakeLists.txt** or **Makefile** to make building Wangscape outside of VS easier, e.g. on Linux.

**Comment by serin-delaunay** [comment]
Thanks so much for doing this Łukasz, I was expecting to wait a long time before any help arrived!

I've pushed some changes that will hopefully fix some of these issues: fixing SFML include capitalisation (https://github.com/serin-delaunay/Wangscape/commit/f9b09e3e778c48ef3ea8bb0a22d80337b9378ddb), adding `<cstddef>` to `common.h` (https://github.com/serin-delaunay/Wangscape/commit/79388b2564219162590df70415c9ebf9eb36ad59), using `const auto&` rather than `auto&` in the Options loader (https://github.com/serin-delaunay/Wangscape/commit/b9a65c17c131825f2e6615f4228bd561778076ff).

I'm not sure how you got a version of the repository without [`MetaOutput.cpp`](https://github.com/serin-delaunay/Wangscape/blob/master/Wangscape/MetaOutput.cpp), [`TerrainImages.cpp`](https://github.com/serin-delaunay/Wangscape/blob/master/Wangscape/TerrainImages.cpp), and [`TileGenerator.cpp`](https://github.com/serin-delaunay/Wangscape/blob/master/Wangscape/TileGenerator.cpp) - they're all on github.

Let me know what else I can do to help, I really appreciate this!

**Comment by hryniuk** [comment]
Now it works like a charm 😄, I successfully built Wangscape on ArchLinux 64bit and generated images from `example` and `example3` dirs. I'll add PR with `Makefile` or `CMakeLists.txt` (more likely) soon.

Oh, I know why I hadn't these files. I have a habit to start `g++` with `-o` option, but I didn't add output file name this time. It's a problem with `g++` interface :wink: - it takes the first `.cpp` file name and removes it to use as an output file before finishing compilation (I think there should be a warning about using file with `.cpp` suffix as binary file name). Sorry for the false alarm.

You can also have [Travis CI](https://travis-ci.org/) builds enabled to check if Wangscape compiles on Linux - I can do it as well, it's just a matter of adjusting small YAML file.

**Comment by hryniuk** [comment]
@serin-delaunay during `CMakeLists.txt` writing I've noticed that `WangscapeTest` uses Visual Studio's CppUnitTestFramework and I cannot build them on Linux. I'm not sure if it's impossible but for sure harder than building it with any of multiplatform unit testing framework like [**CppUnit**](https://freedesktop.org/wiki/Software/cppunit/) or [**Google Test**](https://github.com/google/googletest/).

How do you feel about porting unit tests to one of them?

**Comment by serin-delaunay** [comment]
I expected I would need to port the unit tests once non-VS builds were supported. It looks like Google Test can be integrated with VS using [this extension](https://marketplace.visualstudio.com/items?itemName=vkantchev.GoogleTestRunnerforVisualStudio2015), so I'll work on that in https://github.com/serin-delaunay/Wangscape/tree/google-test.

**Comment by serin-delaunay** [comment]
The tests are all ported to Google Test now, so Travis CI integration can go forward. I've activated the repository in Travis CI, I guess now it just needs `CMakeLists.txt` and `Travis.yml`?

**Comment by hryniuk** [comment]
Yes, I've just added #25 PR with `CMakeLists.txt`. If Google Test branch is merged, I can add UT build to `CMakeLists.txt`. Great! I'll do it in less than 24 hours.

**Comment by hryniuk** [comment]
Or you can do it, e.g I have two examples in my repos:
* https://github.com/hryniuk/toys/blob/master/.travis.yml
* https://github.com/hryniuk/cpp/blob/master/.travis.yml (also [clang-format](https://github.com/hryniuk/cpp/blob/master/.clang-format))

I noticed that [build matrix](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix) is often used for Travis CI configuration, but it's a bit quaint for me.

With complete `CMakeLists.txt`s you can get builds on OSX for free (see: https://docs.travis-ci.com/user/multi-os/).

**Comment by serin-delaunay** [comment]
Thanks for those examples, `cpp`'s was very helpful. I've added a `.travis.yml` to Wangscape ([branch](https://github.com/serin-delaunay/Wangscape/tree/travis)), but TCI doesn't yet have `rapidjson-dev` or `libnoise-dev` whitelisted. `rapidjson-dev` could be replaced with `libjsoncpp-dev`, but there don't seem to be any suitable alternative to `libnoise-dev`. I've opened issues for both of them: https://github.com/travis-ci/apt-package-whitelist/issues/3877, https://github.com/travis-ci/apt-package-whitelist/issues/3878. Not sure what the typical wait time is for these.

**Comment by hryniuk** [comment]
As far as I know RapidJSON is distributed as a **single header file**. If it's not a problem for you, it can be just a submodule of **Wangscape** project (e.g. in `lib/` subdirectory).
It will require only `git submodule update --init` command after cloning the Wangscape repository.

Noise library is a bit bigger, but it can be a submodule as well :).

**Comment by serin-delaunay** [comment]
Rapidjson is more than one header file, but inclusion through a submodule is still a viable option.

As for libnoise, I'm still unsure exactly what the requirements are for an MIT-licensed application to comply with an LGPL library's requirements. I think a submodule would be OK, preferably built separately and linked dynamically.

On the other hand, both libraries have already passed the automatic stage of Travis CI whitelist addition, so it might not be long before they're added. Since neither of us are having trouble building or running tests at the moment, it's probably worthwhile to wait a day or two before setting up submodules.

**Comment by serin-delaunay** [comment]
Closing this for nowm since in theory it will now build on MacOS (at least with gcc), and the remaining issues are Travis-CI issues rather than Linux/MacOS issues.
